// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4NcbYPZmGEavnW_xtLaYfe5g0wN_J2Mk',
    appId: '1:466661665851:web:e30e7c9afbbdbba96bc01e',
    messagingSenderId: '466661665851',
    projectId: 'reddit-clone-afee1',
    authDomain: 'reddit-clone-afee1.firebaseapp.com',
    storageBucket: 'reddit-clone-afee1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBASfGhV_RcxWxj1oKkz238v1GbsV-3fGo',
    appId: '1:466661665851:android:950a096c342f82916bc01e',
    messagingSenderId: '466661665851',
    projectId: 'reddit-clone-afee1',
    storageBucket: 'reddit-clone-afee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDra3I9vjTUo0LqCK_xN8qybeLs8W2YlC8',
    appId: '1:466661665851:ios:c2cd01e2d8c7ea1b6bc01e',
    messagingSenderId: '466661665851',
    projectId: 'reddit-clone-afee1',
    storageBucket: 'reddit-clone-afee1.appspot.com',
    iosClientId: '466661665851-0ir8tddvj1cl8dbp9f43vrk7i0880hs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
